/**
 * Detect filetype from file path
 */
export function filetype(filePath: string): string {
  if (!filePath) return ""
  
  const lower = filePath.toLowerCase()
  
  if (lower.endsWith(".ts")) return "typescript"
  if (lower.endsWith(".tsx")) return "typescript"
  if (lower.endsWith(".js")) return "javascript"
  if (lower.endsWith(".jsx")) return "javascript"
  if (lower.endsWith(".py")) return "python"
  if (lower.endsWith(".rs")) return "rust"
  if (lower.endsWith(".go")) return "go"
  if (lower.endsWith(".sh")) return "bash"
  if (lower.endsWith(".bash")) return "bash"
  if (lower.endsWith(".zsh")) return "zsh"
  if (lower.endsWith(".md")) return "markdown"
  if (lower.endsWith(".mdx")) return "markdown"
  if (lower.endsWith(".json")) return "json"
  if (lower.endsWith(".yaml")) return "yaml"
  if (lower.endsWith(".yml")) return "yaml"
  if (lower.endsWith(".css")) return "css"
  if (lower.endsWith(".scss")) return "scss"
  if (lower.endsWith(".less")) return "less"
  if (lower.endsWith(".html")) return "html"
  if (lower.endsWith(".htm")) return "html"
  if (lower.endsWith(".xml")) return "xml"
  if (lower.endsWith(".sql")) return "sql"
  if (lower.endsWith(".vim")) return "vim"
  if (lower.endsWith(".lua")) return "lua"
  if (lower.endsWith(".php")) return "php"
  if (lower.endsWith(".rb")) return "ruby"
  if (lower.endsWith(".swift")) return "swift"
  if (lower.endsWith(".kt")) return "kotlin"
  if (lower.endsWith(".java")) return "java"
  if (lower.endsWith(".c")) return "c"
  if (lower.endsWith(".cpp") || lower.endsWith(".cc")) return "cpp"
  if (lower.endsWith(".h") || lower.endsWith(".hpp")) return "cpp"
  if (lower.endsWith(".cs")) return "csharp"
  if (lower.endsWith(".fs")) return "fsharp"
  if (lower.endsWith(".scala")) return "scala"
  if (lower.endsWith(".r")) return "r"
  if (lower.endsWith(".dart")) return "dart"
  if (lower.endsWith(".elm")) return "elm"
  if (lower.endsWith(".hs")) return "haskell"
  if (lower.endsWith(".clj")) return "clojure"
  if (lower.endsWith(".ex") || lower.endsWith(".exs")) return "elixir"
  if (lower.endsWith(".erl")) return "erlang"
  if (lower.endsWith(".nim")) return "nim"
  if (lower.endsWith(".zig")) return "zig"
  if (lower.endsWith(".v")) return "v"
  if (lower.endsWith(".dockerfile")) return "dockerfile"
  if (lower.includes("dockerfile")) return "dockerfile"
  if (lower.endsWith(".tf")) return "terraform"
  if (lower.endsWith(".nix")) return "nix"
  if (lower.endsWith(".toml")) return "toml"
  if (lower.endsWith(".ini")) return "ini"
  if (lower.endsWith(".conf")) return "conf"
  if (lower.endsWith(".log")) return "log"
  
  // Diff files
  if (lower.endsWith(".diff")) return "diff"
  if (lower.endsWith(".patch")) return "diff"
  
  return ""
}
